export const SYMBOLS = [
  { id: '1', emoji: '💧', label: 'Agua' },
  { id: '2', emoji: '🍎', label: 'Comer' },
  { id: '3', emoji: '🚽', label: 'Baño' },
  { id: '4', emoji: '🛏️', label: 'Dormir' },
  { id: '5', emoji: '😊', label: 'Feliz' },
  { id: '6', emoji: '😢', label: 'Triste' },
  { id: '7', emoji: '😡', label: 'Enojado' },
  { id: '8', emoji: '😨', label: 'Miedo' },
  { id: '9', emoji: '👋', label: 'Hola' },
  { id: '10', emoji: '🙏', label: 'Gracias' },
  { id: '11', emoji: '✅', label: 'Sí' },
  { id: '12', emoji: '❌', label: 'No' },
  { id: '13', emoji: '🚶', label: 'Caminar' },
  { id: '14', emoji: '🏃', label: 'Correr' },
  { id: '15', emoji: '🧹', label: 'Limpiar' },
  { id: '16', emoji: '📖', label: 'Leer' },
  { id: '17', emoji: '👩', label: 'Mamá' },
  { id: '18', emoji: '👨', label: 'Papá' },
  { id: '19', emoji: '🧒', label: 'Hijo' },
  { id: '20', emoji: '🐕', label: 'Mascota' },
  { id: '21', emoji: '🎵', label: 'Música' },
  { id: '22', emoji: '📱', label: 'Teléfono' },
  { id: '23', emoji: '🚗', label: 'Auto' },
  { id: '24', emoji: '🏥', label: 'Doctor' },
];